name: Mi17Audio CI
on:
  push:
    branches:
      - '*'
    paths:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout module
        uses: actions/checkout@v6
        with:
          path: module

      - name: Checkout hyper-audio-rs
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository_owner }}/hyper-audio-rs
          path: hyper-audio-rs

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable-x86_64-msvc
          targets: aarch64-linux-android

      - name: Setup Android NDK
        uses: android-actions/setup-android@v3

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"

      - name: Install cargo-ndk
        run: cargo install cargo-ndk

      - name: Build
        run: ./module/build.ps1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mi17Audio
          path: ./module/Mi17Audio.zip
